name:                HMTI
version:             0.1.0.0
github:              "unnohideyuki/typeinference"
license:             MIT
author:              "UNNO Hideyuki"
maintainer:          "unno.hideyuki@nifty.com"
copyright:           "2017 UNNO Hideyuki"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
synopsis:            Hindley/Minler Type Inference in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/unnohideyuki/typeinference#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  HMTI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HMTI

tests:
  HMTI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HMTI
    - hspec
